export const categoryImagePaths: Record<string, string> = {
  "esports-betting": "/images/categories/esports-betting-v3.webp",
  "sports-betting": "/images/categories/sports-betting-v3.webp",
  poker: "/images/categories/poker-v3.webp",
  "online-games": "/images/categories/card-games-v3.webp",
  "risk-warning": "/images/categories/risk-warning-v3.webp",
  "platform-reviews": "/images/categories/platform-review-v3.webp",
  rankings: "/images/categories/rankings-v3.webp",
  "betting-guide": "/images/categories/betting-guide-v3.webp",
};

const articleImagePaths: Record<string, string> = {
  "esports-market-risk-checklist": "/images/covers/esports-moba-v3.webp",
  "sports-betting-rule-page-template": "/images/covers/football-v3.webp",
  "poker-platform-data-model": "/images/covers/poker-table-v3.webp",
  "online-games-offer-terms": "/images/covers/card-games-rules-v3.webp",
  "risk-alert-entry-verification": "/images/covers/risk-domain-security-v3.webp",
  "guide-responsible-gambling": "/images/covers/risk-domain-security-v3.webp",
  "asia-betting-info-entry-check": "/images/categories/platform-review-v3.webp",
  "asia-sports-betting-rule-differences": "/images/covers/football-v3.webp",
  "asia-esports-betting-data-checklist": "/images/covers/esports-moba-v3.webp",
  "asia-card-games-offer-risk": "/images/covers/card-games-rules-v3.webp",
  "asia-casino-travel-data-check": "/images/categories/platform-review-v3.webp",
  "asia-betting-platform-data-ranking": "/images/categories/rankings-v3.webp",
  "asia-betting-risk-map": "/images/categories/risk-warning-v3.webp",
  "asia-football-betting-timezone-settlement": "/images/covers/football-v3.webp",
  "asia-basketball-overtime-line-check": "/images/covers/basketball-v3.webp",
  "asia-esports-bo-rules-check": "/images/covers/esports-moba-v3.webp",
  "asia-esports-map-pool-update-risk": "/images/covers/esports-fps-v3.webp",
  "asia-poker-rake-withdrawal-check": "/images/covers/poker-table-v3.webp",
  "asia-poker-account-freeze-risk": "/images/covers/poker-table-v3.webp",
  "asia-card-games-valid-bet-guide": "/images/covers/card-games-rules-v3.webp",
  "asia-baccarat-online-risk-check": "/images/covers/card-games-rules-v3.webp",
  "asia-platform-payment-delay-risk": "/images/categories/risk-warning-v3.webp",
  "asia-casino-age-id-requirements": "/images/categories/platform-review-v3.webp",
  "asia-betting-content-source-check": "/images/categories/platform-review-v3.webp",
  "asia-betting-site-checklist": "/images/categories/platform-review-v3.webp",
  "asia-betting-legal-age-reminder": "/images/categories/risk-warning-v3.webp",
  "asia-betting-domain-certificate-guide": "/images/covers/risk-domain-security-v3.webp",
  "asia-betting-customer-service-transfer-risk": "/images/categories/risk-warning-v3.webp",
  "asia-soccer-handicap-basics": "/images/covers/football-v3.webp",
  "asia-football-over-under-check": "/images/covers/football-v3.webp",
  "asia-nba-player-prop-risk": "/images/covers/basketball-v3.webp",
  "asia-f1-weather-safety-car-check": "/images/covers/f1-v3.webp",
  "asia-esports-lol-draft-check": "/images/covers/esports-moba-v3.webp",
  "asia-esports-cs2-map-veto": "/images/covers/esports-fps-v3.webp",
  "asia-dota2-patch-data-risk": "/images/covers/esports-moba-v3.webp",
  "asia-valorant-agent-map-check": "/images/covers/esports-fps-v3.webp",
  "asia-honor-of-kings-lineup-version": "/images/covers/esports-moba-v3.webp",
  "asia-poker-tournament-terms": "/images/covers/poker-table-v3.webp",
  "asia-poker-bot-collusion-risk": "/images/covers/poker-table-v3.webp",
  "asia-niuniu-online-rule-check": "/images/covers/card-games-rules-v3.webp",
  "asia-sangong-online-terms": "/images/covers/card-games-rules-v3.webp",
  "asia-dragon-tiger-entry-risk": "/images/covers/card-games-rules-v3.webp",
  "asia-doudizhu-online-activity-rules": "/images/covers/card-games-rules-v3.webp",
  "asia-platform-review-update-frequency": "/images/categories/platform-review-v3.webp",
  "asia-platform-risk-level-method": "/images/categories/rankings-v3.webp",
  "asia-casino-singapore-data-notes": "/images/platforms/singapore-marina-bay-sands-v3.webp",
  "asia-casino-macau-data-notes": "/images/platforms/macau-mgm-v3.webp",
  "asia-casino-genting-data-notes": "/images/platforms/malaysia-genting-casino-v3.webp",
  "asia-betting-asia-market-overview-2026": "/images/categories/platform-review-v3.webp",
  "asia-betting-entry-change-record": "/images/categories/platform-review-v3.webp",
  "asia-betting-withdrawal-condition-check": "/images/categories/risk-warning-v3.webp",
  "asia-betting-bonus-rollover-terms": "/images/categories/platform-review-v3.webp",
  "asia-betting-payment-channel-risk": "/images/categories/risk-warning-v3.webp",
  "asia-betting-account-freeze-terms": "/images/categories/risk-warning-v3.webp",
  "asia-sports-betting-delay-postponement": "/images/covers/football-v3.webp",
  "asia-football-line-movement-record": "/images/covers/football-v3.webp",
  "asia-basketball-injury-rotation-check": "/images/covers/basketball-v3.webp",
  "asia-esports-roster-change-record": "/images/covers/esports-moba-v3.webp",
  "asia-esports-technical-pause-rules": "/images/covers/esports-fps-v3.webp",
  "asia-lol-side-selection-data": "/images/covers/esports-moba-v3.webp",
  "asia-cs2-live-delay-risk": "/images/covers/esports-fps-v3.webp",
  "asia-poker-cash-table-bankroll-note": "/images/covers/poker-table-v3.webp",
  "asia-poker-kyc-withdrawal-note": "/images/covers/poker-table-v3.webp",
  "asia-card-games-turnover-exclusion": "/images/covers/card-games-rules-v3.webp",
  "asia-baccarat-table-rule-check": "/images/covers/card-games-rules-v3.webp",
  "asia-niuniu-multiplier-rule-note": "/images/covers/card-games-rules-v3.webp",
  "asia-betting-philippines-license-risk-note": "/images/categories/platform-review-v3.webp",
  "asia-platform-review-not-endorsement": "/images/categories/rankings-v3.webp",
  "asia-casino-resort-responsible-gaming": "/images/platforms/singapore-marina-bay-sands-v3.webp",
  "asia-betting-source-verification-workflow": "/images/categories/platform-review-v3.webp",
  "asia-betting-japan-korea-sports-esports-note": "/images/categories/platform-review-v3.webp",
  "asia-betting-risk-disclaimer-placement": "/images/categories/risk-warning-v3.webp",
  "asia-betting-thailand-cambodia-vietnam-note": "/images/categories/platform-review-v3.webp",
  "asia-betting-crypto-payment-risk-note": "/images/categories/risk-warning-v3.webp",
  "asia-betting-malaysia-singapore-casino-note": "/images/platforms/malaysia-genting-casino-v3.webp",
  "asia-betting-football-basketball-settlement-note": "/images/covers/football-v3.webp",
  "asia-betting-live-casino-table-limit-note": "/images/covers/card-games-rules-v3.webp",
};

const topicImagePaths: Record<string, string> = {
  "champions-league": "/images/covers/football-v3.webp",
  "premier-league": "/images/covers/football-v3.webp",
  "chinese-super-league": "/images/covers/football-v3.webp",
  "sports-betting-regulation": "/images/covers/football-v3.webp",
  nba: "/images/covers/basketball-v3.webp",
  f1: "/images/covers/f1-v3.webp",
  "league-of-legends": "/images/covers/esports-moba-v3.webp",
  dota2: "/images/covers/esports-moba-v3.webp",
  "honor-of-kings": "/images/covers/esports-moba-v3.webp",
  cs2: "/images/covers/esports-fps-v3.webp",
  valorant: "/images/covers/esports-fps-v3.webp",
  crossfire: "/images/covers/esports-fps-v3.webp",
  "niuniu-online": "/images/covers/card-games-rules-v3.webp",
  "sangong-online": "/images/covers/card-games-rules-v3.webp",
  "baccarat-online": "/images/covers/card-games-rules-v3.webp",
  "golden-flower-online": "/images/covers/card-games-rules-v3.webp",
  "dragon-tiger-online": "/images/covers/card-games-rules-v3.webp",
  "doudizhu-online": "/images/covers/card-games-rules-v3.webp",
};

export function getArticleCoverImage(slug: string) {
  return articleImagePaths[slug];
}

export function getTopicCoverImage(slug: string) {
  return topicImagePaths[slug];
}

const platformImagePaths: Record<string, string> = {
  "singapore-marina-bay-sands": "/images/platforms/singapore-marina-bay-sands-v3.webp",
  "malaysia-genting-casino": "/images/platforms/malaysia-genting-casino-v3.webp",
  "macau-mgm": "/images/platforms/macau-mgm-v3.webp",
  "las-vegas-casino": "/images/platforms/las-vegas-casino-v3.webp",
};

export function getPlatformCoverImage(slug: string) {
  return platformImagePaths[slug];
}
